### ISSUE TITLE
Plugin Stoped working Overnight

### ISSUE THREAD

**Issue by sebastiangoldstein** [haywirecoder/homebridge-envisalink-ademco#10]
Over 6 months with no issues - now plugin stopped working overnight?
Any suggestions on how to correct?

**Comment by trob-code** [comment]
Did your Envisalink change IP address?

**Comment by sebastiangoldstein** [comment]
No IP address change but when I checked the device I did see this:
EnvisaLink TPI Status - OFFLINE
I would assume that means that nothing can communicate with Envisilink (Alexa, Smarthings, hoobs etc...)
If this is the case I can't be the only one with this issue, correct?
I have reached out to Eyez-On for clarification.

**Comment by sebastiangoldstein** [comment]
I believe I have solved the issue - My Homebridge box (HOOBS on a Raspberry Pie) changed. Its IP address 
I have switched the HOOBS Device to a static IP - I believe that this will correct the issue.

**Comment by sebastiangoldstein** [comment]
So this has been continuing to re-occur. The Envisilink TPI Status keeps on disconnecting stopping all reporting and control.
This is new for me - not sure why this is starting now. The only solution I have found is to restart HOOBS. That causes the TPI to reconnect but after the first command is sent it disconnects again... Any thoughts or solutions???

**Comment by sebastiangoldstein** [comment]
1/17/2021, 8:25:46 PM [Envisalink-Ademco] Arming alarm to Stay (Home).
1/17/2021, 8:25:46 PM [Envisalink-Ademco] Command not successful, no TPI session established.
1/17/2021, 8:25:55 PM [Envisalink-Ademco] Already handling Alarm state change, igorning request.
1/17/2021, 8:25:56 PM [Envisalink-Ademco] Alarm request did not return successful in allocated time. Current alarm status is  READY

**Comment by sebastiangoldstein** [comment]
Still not sure what's going on, byt the TPI connection only works for a short period of time then disconnects. 
What would cause this?

1/18/2021, 9:51:47 AM [Envisalink-Ademco] Missing Heartbeat - Time drift:  54.502 . Trying to re-connect session...
1/18/2021, 9:51:52 AM [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.68, port: 4025
1/18/2021, 9:51:52 AM [Envisalink-Ademco] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
1/18/2021, 9:51:53 AM [Envisalink-Ademco] Command format invalid! command='%00,01,1C08,08,00,****DISARMED****  Ready t'
1/18/2021, 9:51:54 AM [Envisalink-Ademco] Disconnect TPI session
1/18/2021, 9:51:57 AM [Envisalink-Ademco] Session closed unexpectedly. Re-establishing Session...
1/18/2021, 9:51:57 AM [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.68, port: 4025
1/18/2021, 9:51:57 AM [Envisalink-Ademco] Successful TPI session established
1/18/2021, 9:51:57 AM [Envisalink-Ademco] Checking for disconnected session every:  30  seconds.

**Comment by haywirecoder** [comment]
From looking at the transaction, this seem like your are having internal network issues. My suggestion would be following

1. Have you installed anything new that connect to Envisalink module. Remember only one TPI connection is possible at any given time. Not module limit but Envisalink limit.

2. Have you checked internal network gear (switch/router) or recently install a new device? Missing heartbeat does indicate a hard disconnect at the network level. Something is disconnecting sessions--  Last time someone reported similar issue it was old Smarthing module connection coming on and off. Make sure this is the only TPI client. 

3. I don't use HOOBS, have you recently upgraded? Do you have other plug-in that are network dependent? Are they stable?

**Comment by haywirecoder** [comment]
I’m closing this issue because it has been inactive for over a months. Please reopen if you are still encountering this issue.
