### ISSUE TITLE
 "Carbon Monoxide" device type?

### ISSUE THREAD

**Issue by tevans62** [haywirecoder/homebridge-envisalink-ademco#11]
Hi - just started using this yesterday and so far so good, so pleased to see something already existing for this combo of hardware.

HomeKit does have a carbon monoxide characteristics, it would be great to see that sensor type added for this integration.

I may give it a try myself when I have some time, but if its already inflight I do not want to step on anyone.

**Comment by haywirecoder** [comment]
Hi - Great idea, I haven't consider it prior. Will have to determine the panel codes associate with CO events. Will put on it on list and implement when I have the cycles. If you get to it prior, happy to integrate into the main code base.

**Comment by haywirecoder** [comment]
Added CO device type and associated event for Homekit, will be release as part of version 1.1.23.

**Comment by tevans62** [comment]
Thank you for the change - at the risk of be overly precise, HomeKit allows both CO (Carbon Monoxide) and CO2 (Carbon Dioxide) device types.  You added CO (thanks again!) but the device type in the config is "co2".  Also the ReadMe has the device type listed as "carbon monoxide | ...." rather than its short tag.  It might mix some folks up....!

**Comment by haywirecoder** [comment]
Good catch! Updating document and code to align with the proper short tag. BTW ... a manual update will be needed e.g. replace C02 with CO for version 1.1.24.
