### ISSUE TITLE
Armed "Night", but displays "Home"

### ISSUE THREAD

**Issue by 7RDR7** [haywirecoder/homebridge-envisalink-ademco#12]
Thank-you for sharing this plugin! One observation, when arming from the Home app in Night mode, either directly or through automation, the panel arms in Night mode, but the Home app displays Home mode once the panel clears the exit time. Display is inconsistent with the panel status. I'm using a Vista 21IP and an EVL4. Otherwise quite a nice plugin!

**Comment by haywirecoder** [comment]
Hi,
This limitation of EVL module TPI interface with the Ademco panel. The plug-in does send the Ademco panel "Stay" command for "Home" which is a code 3 and "Night" which is code 33. However, the EVL will only provide following states on change. 

00 – Partition is not Used/Doesn't Exist 
01 – Ready
02 – Ready to Arm (Zones are Bypasses) 
03 – Not Ready
04 – Armed in Stay Mode
05 – Armed in Away Mode
06 – Armed Instant (Zero Entry Delay - Stay)
07 – Exit Delay (not implemented on all platforms)
08 – Partition is in Alarm
09 – Alarm Has Occurred (Alarm in Memory)
10 – Armed Maximum (Zero Entry Delay - Away)

As you can see nothing is coming back that indicate difference between night or stay. I left the night button to allow users to arm system in night mode, but there is no clear method to know which state was armed. If you come across another or more recent TPI protocol guide please share, happy to update.

**Comment by 7RDR7** [comment]
Thank-you haywirecoder. I did escalate to Eyezon, and although they support “Night” in their app and hosted service, they did not include it in the local web interface. I appreciate your detailed response. Thanks again for your plug-in, we use it everyday!
