### ISSUE TITLE
Cannot arm "Away", it seems to default to "home"

### ISSUE THREAD

**Issue by mmorim** [haywirecoder/homebridge-envisalink-ademco#15]
First, thank you for this brilliant plugin!
i was really frustrated with Honeywell for offering no options to connect the alarm system to my smart home, and this setup saved the day.

i am however experiencing a very odd issue.
Homekit refuses to "arm away". it somestimes just fails, but more often - it sets it to "home", even though i pressed "Away". same issue when arming directly or via a scene.
disarming works fine, and "arm away" works as well.

logs are below, though not sure they are related - these are the only things i see in the logs.
`
/12/2021, 9:51:21 AMEnvisalink Ademco BridgeEnvisalink-AdemcoArming alarm to Away.
9/12/2021, 9:51:21 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:52:10 AMEnvisalink Ademco BridgeEnvisalink-AdemcoArming alarm to Stay (Home).
9/12/2021, 9:52:10 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:52:43 AMEnvisalink Ademco BridgeEnvisalink-AdemcoDisarming alarm with PIN.
9/12/2021, 9:52:43 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:52:53 AMEnvisalink Ademco BridgeEnvisalink-AdemcoWARNINGAlarm not ready, igorning request.
9/12/2021, 9:52:53 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:53:39 AMEnvisalink Ademco BridgeEnvisalink-AdemcoDisarming alarm with PIN.
9/12/2021, 9:53:39 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:53:46 AMEnvisalink Ademco BridgeEnvisalink-AdemcoWARNINGAlready handling Alarm state change, igorning request.
9/12/2021, 9:53:46 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:53:49 AMEnvisalink Ademco BridgeEnvisalink-AdemcoWARNINGAlarm request did not return successful in allocated time. Current alarm status is  READY
9/12/2021, 9:54:03 AMEnvisalink Ademco BridgeEnvisalink-AdemcoDisarming alarm with PIN.
9/12/2021, 9:54:03 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:54:11 AMEnvisalink Ademco BridgeEnvisalink-AdemcoWARNINGAlready handling Alarm state change, igorning request.
9/12/2021, 9:54:11 AMEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
9/12/2021, 9:54:13 AMEnvisalink Ademco BridgeEnvisalink-AdemcoWARNINGAlarm request did not return successful in allocated time. Current alarm status is  READY
`

**Comment by haywirecoder** [comment]
Hi,
I haven't seen this issue prior, from log error it seem like the command is being rejected by the panel and from your result in another command being executed. What the plug does it executed the command for home/away/stay/off and waits a few seconds to get the status return from Envisalink. If status is return differently than what was send, it would indicate the panel is processing command differently. This could be a panel programming issue...but hard to indicate with just the log above. You have to run a debug session, for a more details output.

Few questions prior: 
1. When you do request away, does the panel/system actually go to away mode? Is the panel actually responding to the command correctly?
2. What panel/system are you using?
3. What version of Homebridge are you using?

**Comment by mmorim** [comment]
hi.
thanks for the quick response! 
you can ignore the "Already handling Alarm state change" warnings, that was because I did not wait long enough for a timeout. i should have cleaned the logs before posting, my bad.

i did further testing, and I think this is potentially an issue with the envisalink module. it seems that arming directly from the eyezon app, sometimes fails and defaults to "stay" instead of away. i need to speak to them first, I believe.

that being said, I still don't understand: 
MEnvisalink Ademco BridgeERROR[Envisalink Ademco Bridge B587@The Lake House@The Lake House@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response

lastly:
1. requesting from the panel works. requesting from eyezon app - intermittent.
2. it's a Honeywell Visata 20iP.
3. it's Hoobs, version 4.0.100, homebridge version 1.3.4

**Comment by haywirecoder** [comment]
Hi,

Your analysis is correct, if eyezon app is behaving intermittently issues, the same issue will occur with the plugin since it is using the same interface.  
The characteristic error -- For now, don't worry - the warning is completely harmless and does not impact the working of the plug-in. I have some clean up that needs to be done, which is causing this error to be generate. It will be corrected on the next release.

**Comment by mmorim** [comment]
sorry for the delay here, i am trying to get a hold of eyezon to get a better understanding of the multiple steps they are recommending we take, so I can fix this.

**Comment by mmorim** [comment]
i was able to solve the "auto arm stay" issue.
there's a setting in the honeywell system, where it defaults to "arm stay" if the system doesnt identify a door openning and closing.
you need to disable that feature on honeywell using the installer code system (very old and annoying system) and then this works flawlessly.
