### ISSUE TITLE
Option to disable chime

### ISSUE THREAD

**Issue by cefoster0** [haywirecoder/homebridge-envisalink-ademco#16]
I have a Visa 20p with voice chime panels. I normally love the feature but there are times (like at night, when a child is sleeping) where I don't want my bedroom panel to have chime on. Is there any way we can expose chime on/off via a Homekit switch, so it can be controlled? it seems to be a global feature for all panels, when one turns it on, the others follow suit. Thank you for the great work!

**Comment by haywirecoder** [comment]
Hi,
I don't have the Vista 20p panel, but all vista panel should response the same code sequence.  From reading the Vista documentation, you can manually toggle by using "user code + 9". If you can confirm that works on your panel... I can add it to the next version.

**Comment by cefoster0** [comment]
Thank you for the consideration! Confirmed on my panel today that user code + 9 toggles chime on and off. The voice settings persisted , so as soon as it turned it back on with the same code it used voice prompt again, which is great. All controllers stopped chiming when the code was in one, exactly what we want. Thank you again for the fast response!

**Comment by haywirecoder** [comment]
1.1.26 includes options to show a chime toggle.

**Comment by cefoster0** [comment]
Thank you so much! Works great!
