### ISSUE TITLE
Display a Switch to Use to Trigger Automations?

### ISSUE THREAD

**Issue by rtkane1015** [haywirecoder/homebridge-envisalink-ademco#18]
First, thanks for your work on this...I've just discovered this plug-in and it's great!  I was wondering if there is any way to expose a switch so that when the alarm goes off, it can be used to turn on lights in the house? Hope that makes sense. Basically, I'm looking to create an automation so that when the alarm sounds, select lights will be turned on.  I can't find a way to do this currently (but perhaps I'm just missing it). Thanks!

**Comment by haywirecoder** [comment]
Hi,

Maybe, I am not completely understanding the request. This is a native functionality of Homekit, what you would do is create Homekit automation, when the alarm is "triggered" you would turn on whatever other Homekit device (e.g. a light).

**Comment by rtkane1015** [comment]
Hi!  Apologies if I'm just completely missing it, but I can't seem to figure out how to do this in HomeKit as there isn't anything for me to use as the trigger. I can see the alarm being passed through to HomeKit, but there's no option for me to use an alarm event as a trigger for other devices. So if someone breaks into the house, I can't seem to find the right sensor/trigger/switch to use to use as the event to turn on other lights.  I appreciate your help, and again apologize if I've just totally missed it.

**Comment by haywirecoder** [comment]
Hi, assuming you have already configure and added the plug-in and alarm icon is already appearing in homekit. This would be step that I would take to create the automation:

To Goto "Add Automation" in the Home App
Select "An Accessory is controlled" 
Press Next
Select the alarm accessory (default would be name "House alarm")
Press Next
Select the "Triggers event" next

— At this point the home app would show you all the accessory in home kit for you to control.

**Comment by rtkane1015** [comment]
Got it! Thanks so much! I was selecting  "when a detector senses something"  and not "when an accessory is controlled". Working now!  Again, thank you for your help
