### ISSUE TITLE
Function key error

### ISSUE THREAD

**Issue by HerbM3** [haywirecoder/homebridge-envisalink-ademco#19]
I am getting this error when I trigger a function key. Any ideas?
[homebridge.log-2.txt](https://github.com/haywirecoder/homebridge-envisalink-ademco/files/7981186/homebridge.log-2.txt)

**Comment by haywirecoder** [comment]
Hi,

Good and Bad new on this front. The good news is this issued corrected in an upcoming version and also correct a few other issues I noted. The Bad news is the functionality of function key had to be migrated to speed key. Some minor configuration change will be needed (Can be done via UI or configuration file). The root issue was the way the code was handling the concept of a push button (which doesn't existing in HomeKit) so simulating the behavior cause unexpected results. 

BTW... if you just using key to Arm/disarm via automation you can directly perform the action on the alarm control itself.

**Comment by HerbM3** [comment]
Thanks for the quick reply. I was hoping to use the speed / function key to trigger alarm via an automation. I wanted my Aqara vibration sensors to enable the fire key which then would setoff the alarm. I think the 20P can be set so the fire alarm is audible.

I'm new to this... Re-read your reply... So if HomeKit doesn't register a button push, can the speed keys still register as a switch like it currently does in the Home app?

**Comment by haywirecoder** [comment]
Hi,

Ah, I understand your goal. Yes the  speed keys can trigger a panic or fire key sequence -- I had similar need to trigger the alarm. I have also created a concept of a macro -- if you know the keypad code sequence you can also trigger the event directly.  My goal is by this weekend to release the code. If you want to try it prior can download the code directly from the repo.

**Comment by HerbM3** [comment]
Awesome! You're my hero ;) Could not be more timely. We've had three break-ins in our small neighbourhood in a month.

I'm trying to achieve two goals:
1. Trigger the alarm via HomeKit - which you've solved.
2. Trigger Homekit devices (lights) if the wired contacts trigger the alarm. Possible?

**Comment by haywirecoder** [comment]
Yes, you can add an automation today to trigger event when alarm is triggered.  Look at the close issue #18 it provide steps.

Another routine/automation that heard a lot and why I created the plug-in the first place, is auto arm of alarm at night. This routine that had been running in my environment since the begin.

**Comment by HerbM3** [comment]
So cool. Thank you. I cannot wait to get this all working. I'll keep you up to date. 
I might download the code, but I'm kind of a noob. So we'll see...

**Comment by haywirecoder** [comment]
Hi,

The new version has been release. It should correct issue that you have with function keys, now speedkeys.

**Comment by haywirecoder** [comment]
Please post new issue if issue is still present after. Assumption is this issue was fixed with new version.
