### ISSUE TITLE
Add Device Model "Vista 21ip"

### ISSUE THREAD

**Issue by 7RDR7** [haywirecoder/homebridge-envisalink-ademco#21]
Thanks for the great plugin! In the model list it does not include the Vista 21ip in the pull down menu. I've been using this model panel with your plugin and it works very well!

**Comment by haywirecoder** [comment]
Nice catch, Both 20p and 20IP should act the same for zone padding (e.g. Must be 2 digits). So, it safe to select Vista 20p ( but not 128). I have posted the new config.scheme.json which adds the options and will push new update during the weekend.  BTW.. the model selection is used for description model...so, it will auto correct when restart with the new selection.

**Comment by 7RDR7** [comment]
Thank-you!

**Comment by haywirecoder** [comment]
Version 1.2.1 release.

**Comment by 7RDR7** [comment]
Thanks for the update!
