### ISSUE TITLE
TPI disconnecting

### ISSUE THREAD

**Issue by joshjohanning** [haywirecoder/homebridge-envisalink-ademco#23]
Using **1.2.1**.

I've been seeing these errors and I have to reboot my homebridge instance every 1-2 days.

I don't have any other software interacting with the Envisalink; no Home Assistant or anything like that. 

From logs:

```
[26/02/2022, 08:55:45] [Envisalink-Ademco] Disarming alarm with PIN. [Partition 1]
[26/02/2022, 08:55:45] [Envisalink-Ademco] EnvisaLink:  Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[26/02/2022, 08:55:55] [Envisalink-Ademco] Alarm request did not return successful in allocated time. Current alarm status is  ARMED_STAY
[26/02/2022, 08:56:05] [Envisalink-Ademco] Envisakit Module: Command not successful, no TPI session established.
```

And then sometimes I'll just see this randomly in the logs where it disconnects and of course afterwards it doesn't work:
```
[26/02/2022, 23:01:18] [Envisalink-Ademco] Disconnect TPI session
[26/02/2022, 23:05:43] [Envisalink-Ademco] Disarming alarm with PIN. [Partition 1]
[26/02/2022, 23:05:43] [Envisalink-Ademco] Envisakit Module: Command not successful, no TPI session established.
[26/02/2022, 23:05:53] [Envisalink-Ademco] Alarm request did not return successful in allocated time. Current alarm status is  ARMED_STAY
```

Any thoughts?

**Comment by haywirecoder** [comment]
Hi,

This is associated with a low level TCP steam error which indicating a network issue between your Homebridge and EVL4. You can review the close issue #7 to see debugging suggestion.

**Comment by joshjohanning** [comment]
I downgraded to [v1.1.26](https://github.com/haywirecoder/homebridge-envisalink-ademco/releases/tag/v1.1.26) and don't seem to be having the issues anymore. I'm on day 4 of not having to reboot the HomeBridge server vs. every day / every other day before. 

It looks like this morning the TPI session did disconnect, but it was able to reconnect. I didn't see that before honestly when on `1.2.1` - it just disconnected and then I would have to reboot the homebridge server. 

> [02/03/2022, 04:53:32] [Envisalink-Ademco] Missing Heartbeat - Time drift:  51.799 . Trying to re-connect session...
> [02/03/2022, 04:53:32] [Envisalink-Ademco] Error: read ECONNRESET
>     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
>   errno: -104,
>   code: 'ECONNRESET',
>   syscall: 'read'
> }
> [02/03/2022, 04:53:37] [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.10, port: 4025
> [02/03/2022, 04:53:37] [Envisalink-Ademco] Successful TPI session established
> [02/03/2022, 04:53:37] [Envisalink-Ademco] Checking for disconnected session every:  30  seconds.

**Comment by haywirecoder** [comment]
Ah,

From what your indicating 1.1.26 is getting disconnected however plug-in is reconnect due to lost of connection, thus reducing the impact random disconnects. There are two different issues:

1. The EVL module is dropping connect even in prior versions, which suggest you are have a network issues. TPI connect shouldn't be dropping on daily basis this is an issue that should be address. The auto-reconnect was design to help with occasional network hiccups the frequency you are reporting will cause other issues. 
2. In prior version the plug-in auto re-connected correctly. I reviewed the code and configuration and can confirm 1.2.x did introduce a bug in this re-connection logic. The bug is in two parts, first a typo in the Configuration files for the attribute autoConnect name and other swapping of functions to re-create the connection. Both of these I have corrected, will post and will be include in the next build (1.2.2). 

I will update this issue when 1.2.2. has been release.

**Comment by joshjohanning** [comment]
1. I haven't had an `ECONNRESET` since Feb 26 - other than today's (Mar 2) of course, so it's not necessarily daily, but understood. 

2. That's great to hear! Thank you for looking into it. Looking forward to `1.2.2`

**Comment by HerbM3** [comment]
All of a sudden, I am having constant TPI disconnects:

EnvisaLink:  Error: connect ETIMEDOUT 192.168.1.154:4025
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.154',
  port: 4025
}

**Comment by haywirecoder** [comment]
@joshjohanning 
Release 1.2.2 with correction to the auto re-connect logic. You should see following line if the auto re-connect is enabled. If not go into the configuration UX and make sure the setting is enabled, which should result in setting autoReconnect=true and sessionWatcher=true in the configure.

[05/03/2022, 16:13:24] [Envisalink-Ademco] Successful TPI session established.
[05/03/2022, 16:13:24] [Envisalink-Ademco] Checking for disconnected session every: 30 seconds.

I tested a few times by simply disconnecting my envisalink module network cable and re-connecting the cable. The logic seem to be working as design.

**Comment by joshjohanning** [comment]
Awesome! Just installed. Will monitor the logs and see if it works as expected from my side 😄

**Comment by joshjohanning** [comment]
Seems to work as expected. Closing!

> [07/03/2022, 05:55:15] [Envisalink-Ademco] Missing Heartbeat - Time drift:  58.806 . Trying to re-connect session...
> [07/03/2022, 05:55:15] [Envisalink-Ademco] EnvisaLink:  Error: read ECONNRESET
>     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
>   errno: -104,
>   code: 'ECONNRESET',
>   syscall: 'read'
> }
> [07/03/2022, 05:55:20] [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.10, port: 4025
> [07/03/2022, 05:55:21] [Envisalink-Ademco] Successful TPI session established.
> [07/03/2022, 05:55:21] [Envisalink-Ademco] Checking for disconnected session every: 30 seconds.
