### ISSUE TITLE
Pin to unarm

### ISSUE THREAD

**Issue by damdude** [haywirecoder/homebridge-envisalink-ademco#24]
Is there a way to setup this plug-in so that it would require pin to unarm in Apple home app but can arm the system without pin ?

**Comment by haywirecoder** [comment]
Hi,

To my knowledge this is not feature of Home app and/or other 3rd party Homekit applications.

**Comment by joshjohanning** [comment]
> Is there a way to setup this plug-in so that it would require pin to unarm in Apple home app but can arm the system without pin ?

I agree, I don't think there's anything in HomeKit that is going to intercede with having to enter in a pin on disarm.

Not super helpful to you if trying to stay in the HomeKit ecosystem, but if this is must have functionality, this is how the [EyezOn Alexa skill](https://www.amazon.com/Envisacor-Technologies-Inc-EyezOn/dp/B07NDZMH55) works - it arms without a pin, but when you disarm it asks for a pin.

**Comment by haywirecoder** [comment]
Yup, its handful of options that still missing in homeKit. The only thing, I can recommended not using the master user or installer code in the configure file. Create a separate alarm user with the proper less access permissions and ofcourse lock down access to your Homebridge.
