### ISSUE TITLE
No TPI session established.

### ISSUE THREAD

**Issue by HerbM3** [haywirecoder/homebridge-envisalink-ademco#25]
I had to do a complete Ubuntu 18 reinstall. Now the plugin no longer seems to work.

EnvisaLink:  Error: connect ETIMEDOUT 192.168.x.xxx:4025
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.x.xxx',
  port: 4025
}

**Comment by haywirecoder** [comment]
Hi

This is a low level network error from Nodejs when plug-in is trying to connect to EVL.  

1. Confirm that no other devices are connected to EVL, only one device can be connected to the module.
2. Confirm that TPI is enable on EVL
3. On the same device that you're running Homebridge, I would try to telnet into port 4025 to see if you are able to connect and/or do trace to see why a TCP handshake not completing.

**Comment by HerbM3** [comment]
Here is the result of telnet:
Trying 192.168.xx.xxx
Connected to 192.168.xx.xxx.
Escape character is '^]'.
Login:
uTimed Out!
Connection closed by foreign host.

**Comment by HerbM3** [comment]
I also am running old firmware - Version: 01.04.176A. I cannot find the update ling on the EVL4 local page, not on the Eyezon page. Obviously not your problem, but it might be causing and issue.

**Comment by haywirecoder** [comment]
Hmm...
Telnet is indicating you can connect to EVL module and you are getting prompted for login, assuming this is being done on the terminal Homebridge server.

1. Confirm your configuration for the plug-in looks something like this:
            "name": "Envisalink-Ademco",
            "host": "192.168.X.Y",
            "port": 4025,
            "deviceType": "15P",
            "password": "user",
            "pin": "XXXX",
            "changePartition": false,
            "openZoneTimeout": 30,
            "heartbeatInterval": 30,
            "commandTimeOut": 10,
            "autoReconnect": true,
            "sessionWatcher": true,
            "chimeToggle": true,
            "maintenanceMode": false

The password should always be "user", unless it was changed on EVL4 module. You can also just use the UI and press save to assure everything is set correctly.

2. Additional questions

- You mention this was a rebuilt, I assume this was working prior to this rebuild? If so the firmware shouldn't be a factor.
- Confirm your running latest version of Homebridge, Nodejs and the plug-in (1.2.2 was release today).
- This error occur at startup of the plug-in?

3. If this is occurring at start up place Homebridge in debug mode and post resulting output. Note: The debug mode will print out a lot more detail, so you want to review and make sure item such as your PIN is XXXX out.

**Comment by HerbM3** [comment]
I found what it was by reading the debug several times... I'm totally embarrassed. User error. I had a "1" in the IP triad octet, instead of the correct two digits. I was myopically focused on the last three digits.

Apologies for the headache. I appreciate the support.

**Comment by haywirecoder** [comment]
Glad you found the issue :-). Happy alarming...
