### ISSUE TITLE
Turning off triggered alarm

### ISSUE THREAD

**Issue by HerbM3** [haywirecoder/homebridge-envisalink-ademco#26]
First, Haywirecoder, thank you for this plugin and enduring me.

Does the plugin allow for turning off the alarm once it has triggered? My guess is "no". If it does, then my setup isn't working.

**Comment by haywirecoder** [comment]
Hi,

No, when alarm is triggered it is not a simple key sequence. Usually to clear an alarm --  the user has to entering the PIN, waiting for a response from the panel and entering PIN again.
