### ISSUE TITLE
How to I arm/disarm the entire system? No control panel interface.

### ISSUE THREAD

**Issue by sebastiangoldstein** [haywirecoder/homebridge-envisalink-ademco#3]
haywirecoder,
Thanks for all you work on this. I am relatively new to hombridge so my issue may likely be something simple that I am missing.
Using HOOBS and I added my Envisilink 3 Ademco (Honeywell Vista-20)to HOOBS.
All of my Alarm sensors show up in Homekit.
BUT, I Can't figure out how to Arm and Disarm the alarm.
It looks like you can arm each sensor individually but I can't figure out how to add a control panel interface to arm the entire system or get status. Should a panel have just appeared in Apple Home or do I have to add the Panel somewhere?
Additionally - the reporting from all fo the added sensors. is sporadic showing arming and disarming at odd intervals.
Any help would be helpful. 
Thanks,
-Sebastian

**Comment by haywirecoder** [comment]
Hi,
In homekit you should have an alarm icon, it will be the same as the partition name you defined in the configuration file. This is where you can arm and disarm the system. The individual sensors will just communicate status of those sensors (hence why that an optional configuration) and you can create automation based on those sensors (if you wish). You shouldn't have to directly intact with them in regards to arm and disarming your system.
Make sure you have the below entry in the partition section of configuration (note:  you can name "House alarm" anything you wish)

[
    {
        "name": "House Alarm"
    }
]

**Comment by sebastiangoldstein** [comment]
@haywirecoder, That solved My issue. Not sure how I missed naming the system.
Thanks. This is an amazing Plugin. It is my favorite part of my new Homebridge setup!
Thanks.
