### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by Vince-Vmar** [haywirecoder/homebridge-envisalink-ademco#30]
I know this has been discussed at great length, but I wanted to add my experience. 
Running version 2.0.1 and recently updated the Envisalink module to version 203.

I know that 2 devices cannot talk to the Envisalink module at the same time. But what has been happening to me, and this has happened a few times, as soon as I connect to the module via the eyez-on portal, homebridge disconnects and goes in to the error loop every 5 seconds posting the connection error. OK, fine, to be expected. But once I disconnect the web connection homebridge is never able to reconnect. I tried using the reboot command from the eyez-on web portal, then quickly close the page as the module reboots hoping that the plugin will establish the connection, but no, the errors continue. 

The only way I can get it to reconnect is to open the alarm box and physically disconnect the 12v supply to the Envisalink module and reset it that way. Then it reconnects to the plugin and all is fine. 

As a really gross hack I installed a momentary switch on the side of the alarm box that I can push to disconnect the 12v supply and reset the module. 

Am I missing something or should the plugin be able to reconnect once the web page connection is closed. I realize this is probably a problem with the Envisalink module not closing the connection to the webpage and thus blocking the homebridge module from establishing a connection. Does anyone know a way to force the module to free up the TPI connection?

**Comment by haywirecoder** [comment]
Hi,

 Few comments:

1. The eye-on portal portal, should not impact your TPI connection. The TPI standard for Third Party Interface and should only be used external processes to the Eye-z service.  In addition unless you have changed the local user/password nothing outside your network can use this connection.  I have a EV3, with a static IP and Enable TPI Session Alerts. My Envisalink Application Firewall is still enable based on EnvisaLinkTPI-ADEMCO-1-03 document. 

2. The plug-in uses the TPI interface (look at section EnvisaLinkTPI-ADEMCO-1-03 section 2.2. in the doc folder for details about network TPI interface) and does try to auto re-connect. According to the document "The Envisalink will close the connection if the client closes its side."
