### ISSUE TITLE
Start up error - Misconfigured Alarm Zone Bypass switch definition Zone Bypass ignoring

### ISSUE THREAD

**Issue by Landonthi** [haywirecoder/homebridge-envisalink-ademco#31]
Getting an error in home bridge as follows - Misconfigured Alarm Zone Bypass switch definition Zone Bypass ignoring.
I am unable to further troubleshoot what is causing the error. Looking for some assistance please. Thanks

Logs:

10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Configuring Honeywell VISTA-20P for Homekit...
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Misconfigured Alarm Zone Bypass switch definition Zone Bypass ignoring.
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Partition configured: 1
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Zone accessories configured: 1
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Bypass accessories configured.
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Speed keys accessories configured.
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.111, port: 4025
Setup Payload:
X-HM://00247OG5HMHU3

[10/19/2022, 10:20:03 PM] Homebridge v1.5.0 (HAP v0.10.4) (Homebridge EC62) is running on port 51675.
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Successful TPI session established.
[10/19/2022, 10:20:03 PM] [Envisalink-Ademco] Checking for disconnected session every: 30 seconds.
Plugin Config:

{
            "name": "Envisalink-Ademco",
            "host": "192.168.1.111",
            "port": 4025,
            "deviceType": "20P",
            "password": "user",
            "pin": "4156",
            "changePartition": false,
            "openZoneTimeout": 30,
            "heartbeatInterval": 30,
            "commandTimeOut": 10,
            "autoReconnect": true,
            "sessionWatcher": true,
            "chimeToggle": false,
            "envisalinkFailureSuppress": false,
            "maintenanceMode": false,
            "partitions": [
                {
                    "name": "House",
                    "partitionPin": "4156"
                }
            ],
            "zones": [
                {
                    "name": "Mud Door",
                    "partition": "1",
                    "zoneNumber": "4",
                    "sensorType": "door",
                    "bypassEnabled": false
                }
            ],
            "bypass": [
                {
                    "enabledbyPass": false
                }
            ],
            "speedKeys": [
                {
                    "name": "Test",
                    "speedcommand": "A"
                }
            ],
            "platform": "Envisalink-Ademco"

Environment:
Docker 20.10.3-1308

Plugin Version: V 2.0.2
Homebridge Version: V 1.5.0
Node.js Version: 12.22.7-2029 (Installed in Synology DSM)
NPM Version:
Operating System: Synology Nas DSM 7.1.1-42962 Update 1
Docker reports OS: Ubuntu Focal Fossa (20.04.4 LTS)

**Comment by haywirecoder** [comment]
Hi,
The error message can be ignored since bypass switch is disabled. It is caused by a logic flow that is no longer needed and will be removed in the next release. If you want to remove it prior to the next release; delete the following section in the configuration:

"bypass": [
{
"enabledbyPass": false
}

**Comment by haywirecoder** [comment]
Update version 2.0.3 corrected the "Misconfigured Alarm Zone Bypass" message  if Bypass switch is not configured.
