### ISSUE TITLE
No motion events

### ISSUE THREAD

**Issue by tomhoag** [haywirecoder/homebridge-envisalink-ademco#33]
What alarm states should generate motion events?

Presently I’m not getting any motion events in HomeKit while the alarm is in states Home, Away, Night or Off.

**Comment by haywirecoder** [comment]
Hi,

Not too clear on your question. In general if you're keypad register a motion, the plug will get the motion event. In my observation here are the various state:

1. If alarm system is Off: You will get motion events in HomeKit. Keep in mind the alarm panel does not provide fault restore event. So, the motion will stay active until the zone timeout value is expired.

2. If alarm system is Night/Stay: Depending on configuration of your system. If the motion sensor is monitored your system will sound the alarm and Homekit will register alarm event.   Homekit will **not** register activity from motion sensor when system not off. This is a limitation of the alarm panel.

3. If alarm system is Arm: Alarm will sound (assuming of course motion sensor is being monitored). Homekit will **not** register activity from motion sensor when system not off. This is a limitation of the alarm panel.

**Comment by tomhoag** [comment]
Thanks and sorry about the typos (I’ve edited the question).  HomeKit is not receiving motion events while the alarm is off.  I will verify that the motion detectors are working and configured in the home alarm properly.

**Comment by haywirecoder** [comment]
Np, I have two motion detector in my configuration and they triggers a motion in Homekit. Your configuration should look something like the following:

"zones": [
 {
                    "name": "Motion Sensor",
                    "partition": "X",
                    "zoneNumber": "YZ",
                    "sensorType": "motion",
                    "bypassEnabled": false
},
]

Where X is partition number and YZ is the zoneNumber. Ofcourse as you suggested make sure they are triggering motion in the panel.
