### ISSUE TITLE
Zone battery?

### ISSUE THREAD

**Issue by samwelnella** [haywirecoder/homebridge-envisalink-ademco#34]
Hi,

None of my sensors have a low battery service in HomeKit. Is there any config change or something to enable this? I didn’t see anything in the readme.

**Comment by haywirecoder** [comment]
Hi,

I am not clear on your question.  If the panel send a  RF LOW BATTERY, the sensor will display a low battery icon in Home (e.g. Homekit control application). If the sensor isn't in low state the Homekit control application will not provide indicator (e.g. the battery Icon).  Are you indicating your panel is giving an RF LOW BATTERY but there no indicator

**Comment by samwelnella** [comment]
Yes the panel is indicating that a zone has low battery but there is no indication in HomeKit that there is a low battery

**Comment by haywirecoder** [comment]
Few questions:

1. What panels are you using? and Envisalink module?
2. What type of sensor/model is in Low Battery?
3. Please place homebridge in debug mode. The module should output  "Envisakit Operation: " details in the log. Can you post the output lines.  I am specifically looking for updatekeypad and cidEvent events. 

Since, I don't have any of sensors in Low battery (or near dead battery), it hard to replicate this use case at the moment but hopefully from the logs I determine the possible issue.

**Comment by haywirecoder** [comment]
One more item: 

Please refer to page 9 of the EyezonEnvisalinkHoneywellInstallationGuide.pdf (I posted it on the Doc folder for easy finding). Please assure you have *67 - RF Low Battery Reporting and *75 - RF Low-Bat Restoral Reporting enabled. Envisalink module will not receive alert of the RF battery status unless these reporting options are enabled. If Envisalink doesn't receive the alert the the module will not receive the alert.

**Comment by samwelnella** [comment]
> What panels are you using? and Envisalink module?

I have a Vista 20p panel and a Envisalink 4 running firmware 01.04.184A

> What type of sensor/model is in Low Battery?

The sensor in low battery is a door sensor.

> Please place homebridge in debug mode. The module should output "Envisakit Operation: " details in the log. Can you post the output lines. I am specifically looking for updatekeypad and cidEvent events.

This is the relevant output:

`[07/01/2023, 10:03:16] [Envisalink-Ademco] Command | %00,01,C008,12,00,LOBAT 12                        $,00,01,C008,12,00,LOBAT 12                         | Acknowledged
[07/01/2023, 10:03:16] [Envisalink-Ademco] Envisakit Operation: updatekeypad
[07/01/2023, 10:03:16] [Envisalink-Ademco] systemUpdate: Status changed -  {
  partition: '01',
  code: {
    icon: [ 3, 14, 15 ],
    zone: '12',
    beep: 'off',
    txt: 'LOBAT 12                        '
  },
  status: 'Virtual Keypad Update',
  keypadledstatus: {
    alarm: false,
    alarm_in_memory: false,
    armed_away: false,
    ac_present: true,
    bypass: false,
    chime: false,
    not_used1: false,
    armed_zero_entry_delay: false,
    alarm_fire_zone: false,
    system_trouble: false,
    not_used2: false,
    not_used3: false,
    ready: false,
    fire: false,
    low_battery: true,
    armed_stay: true
  },
  mode: 'ARMED_STAY'
}`

Looking at the log output it looks like the plugin is receiving a LOBAT status on zone 12 which is the same zone that shows low battery on the panel.

**Comment by haywirecoder** [comment]
Hi,

Thanks for the output. The Virtual Keypad which is associated with updateKeypad event, is not where the plug-in is expecting the receive a low battery event, it is expecting that from the TPI alert (i.e. the Envisalink module itself). 
I just post an updated to envisalink.js and index.js incorporating the keypad as additional source for the battery status. Please download and replace those two files and see if it give you the Homekit update.

Please keep in mind the Virtual keypad is mirror of a traditional keypad so it doesn't support notifications rather just constant stream keypad updates. This code update is using keypad "low_battery" status icon and matching the "LOBAT" description field to determine if there a low battery event on the panel. This is a back up method -- You should consider enabling alerting on Envisalink itself as indicated above. Some other events can only really be captured using the TPI alert (cid event).

**Comment by samwelnella** [comment]
Hi,

Thanks for the code changes. My door sensor now shows battery low when I view its accessory details in the Home app.

**Comment by haywirecoder** [comment]
Awesome! It will be included in the next release. Keep in mind when you change the battery and clear the event. It will take about about 30sec-1 min (or openZoneTimeout to  openZoneTimeout  + 30 sec) for it disappear in HomeKit. The is using the same timeout process as zone faults since the panel virtual keypad doesn't give information when the fault are cleared, so the plug-in is simply aging the event.

**Comment by haywirecoder** [comment]
Feature added as part of v2.0.4
