### ISSUE TITLE
Zones automatically closing

### ISSUE THREAD

**Issue by boognishbeliever** [haywirecoder/homebridge-envisalink-ademco#39]
Thank you for all your work on this plugin! It has been serving me well for years.

After the most recent update, all zones are automatically closing after approx 20sec.

Once zones automatically close, changing the state of any zone will cause all zones to refresh and show their current state, but they all return to 'closed' after approx 20sec.

During my troubleshooting, I have confirmed that the envisalink and my keypad sees zones as 'open,' but HomeKit displays them as closed.

Please let me know if there is additional logging I can collect to figure out why my zones are automatically closing.

[config.txt](https://github.com/haywirecoder/homebridge-envisalink-ademco/files/11444572/config.txt)

**Comment by haywirecoder** [comment]
Hi,

I am not able to replicate the issue. When I open the zone, it stays faulted until I close it.  
1.  Unless you are using bypass fuctionality, I would remove the "bypassEnabled" in two entries. The only reason I am suggesting is bypass is using "switches" and depending on Homekit client this may make zone appear open or close since the power state is off if not bypass.
2. Please place homebridge in debug state, fault a zone and let it auto close as your indicatin and post the envisalink-ademco outputs.  Please be mindful of PIN that could be display.

**Comment by boognishbeliever** [comment]
Thank you for taking the time to look at this. I know it is probably something I am doing wrong.

I have removed the bypass entires.

Attached is a log file of the activity I am seeing. While this log was being complied, zone 7 never physically closed, but it appeared to close, and remain closed in the Home app.

Triggering the motion sensor (zone 5) appears to be related to zone 7 'closing'...... when this happens I am seeing"Zone Status Change Zone Time Out" in the logs.

Any help is appreciated. 

[homebridge_zones_automatically_closing_39.log.txt](https://github.com/haywirecoder/homebridge-envisalink-ademco/files/11447287/homebridge_zones_automatically_closing_39.log.txt)

**Comment by haywirecoder** [comment]
Hi,

Thanks for the logs. Based on the logs I believe the code is not handling single digit zone correctly base on various method it determine if zone is still in fault state.  I corrected the issue and posted an updated envisalink.js. If you want to test you can replace this file in your installation. I usually let it sit in my installation before posting a new package so it will be a week or so before I release as new version.

**Comment by boognishbeliever** [comment]
and it works! THANK YOU THANK YOU THANK YOU.

I thought I was going crazy. My homebridge has been rebuilt and door contacts are staying 'open.'

I appreciate all your help.

**Comment by haywirecoder** [comment]
Release version 2.0.7 corrects this issue.
