### ISSUE TITLE
No alarm system mode command is supported for partition status NOT_READY.

### ISSUE THREAD

**Issue by arcticfoxwp** [haywirecoder/homebridge-envisalink-ademco#41]
Hello,

I can not see a disucssion / help page, so forgive me if this isn't an issue, and the problem is on my end.

With the latest update I started getting the below in the Homebridge logs. Config has not changed.

[Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.

Any help would be appreciated.

**Comment by haywirecoder** [comment]
Hi 

Can you provide context as to when you are receiving this error? Such as what actions are being performed when you get this error. In addition a bit of detail about your configure would also be helpful.

**Comment by arcticfoxwp** [comment]
Hello, thanks for the reply. I also want to say thank you for creating and maintaining such a great plugin.

Here is my log the last time this happened. I have an automation for a 6:00 am disarm. And at 10:27 we left home and the system armed to stay.

My configuaration is very simple. Honeywell Vista 21IP. No partitions, no zones, no sensors added to Homebridge. Just the panel to Arm / Disarm.

[6/1/2023, 6:00:02 AM] [Envisalink-Ademco] Disarming alarm with PIN. [Partition 1]
[6/1/2023, 9:33:53 AM] [Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.
[6/1/2023, 9:34:26 AM] [Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.
[6/1/2023, 10:07:03 AM] [Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.
[6/1/2023, 10:16:32 AM] [Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.
[6/1/2023, 10:18:51 AM] [Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.
[6/1/2023, 10:20:26 AM] [Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.
[6/1/2023, 10:27:56 PM] [Envisalink-Ademco] Arming alarm to Stay (Home). [Partition 1]

**Comment by haywirecoder** [comment]
Hmm...

This is indeed an is an odd one. The only place in the code this message is generated is when Homekit requests the alarm control to change, which is either cased by user interaction or automation.  I am assuming these log entries are in orange/yellow indicating a warning? The change in the previous version was to correct to get the plug proper process to state information for zone 1- 9...so this just appears it related to a zone in those areas.


1. Do have any other automation that touches this alarm?
2. Does this happen every day? If so can you turn-on Homebridge into debug mode and post the debug information?

**Comment by arcticfoxwp** [comment]
1. I have automations for arming at night, disarming in morning and then arm away. 
2. Does not happen every day.

You're right it is orange warning. Would this warning generate if a homekit automation was trying to arm the system, but the system wasn't ready? (ie: a door was open?)

**Comment by haywirecoder** [comment]
Correct, usually that indicates a system is not ready due to a fault (e.g. door open, window open...etc). The log entry would only appear if the partition state is being requested to be changed (arm, disarm..etc) and something is wrong (e.g. a fault).
Don't understand what's triggering it randomly.  The debug log would help, but they generate a lot of entries.

**Comment by arcticfoxwp** [comment]
Let me investigate, I think this could be my away automation trying to trigger.

Could the wording of this warning be changed to make it more obvious what is happening? Something like:

State cannot be changed, fault detected. Please use alarm system keypad or bypass the open zones.

Or even an entry before to show what the system is trying to do: Arming alarm to Stay requested, then the warning?  

Not sure if this is possible. Thanks again!

**Comment by haywirecoder** [comment]
In agreement,  rewording to reduce confusion. 

"The alarm system was not ready, and a zone fault was detected. The request for state change of ${homekitState} is ignored, review the alarm system keypad for more information."

Where ${homekitState} is the state it was attempting to change to... The change is already posted in /accessories/partitionAccessory.js if you want to use it.

**Comment by arcticfoxwp** [comment]
Awesome! Thanks a lot.

I will wait for a plugin update as I don't know how to make the change - I'm in over my head just getting Homebridge to run as it is. :)

**Comment by haywirecoder** [comment]
The enhancement to the message has been published. Hopefully, it helps determine what causes the random messages.

**Comment by arcticfoxwp** [comment]
Thanks. Great work.

**Comment by arcticfoxwp** [comment]
I have figured my problem out, (it's on my end) but the text for me has stayed the same. (I updated the plugin a few days ago)

[6/11/2023, 11:33:56 PM] [Envisalink-Ademco] No alarm system mode command is supported for partition status NOT_READY. Please use alarm system keypad or bypass the open zones.

**Comment by haywirecoder** [comment]
Hi, 

Glad you figured it out. 

Don't believe you're running the correct version (2.0.8).  That text doesn't appear anywhere in the code base anymore. Perform a search of my install it doesn't area in any of the files.

**Comment by arcticfoxwp** [comment]
Yep I am

Plugins
[Up To Date]

Installed
[ Verified](https://github.com/homebridge/homebridge/wiki/verified-Plugins)
Homebridge Envisalink Ademco
homebridge-envisalink-ademco v2.0.8

**Comment by haywirecoder** [comment]
Hmm... I am actually at a loss.  Nothing in the code has that text anymore.  You may want to do a search on the installation and determine if something is not installed correctly.  On the UNIX-like system, you can search via the command line using...
grep "No alarm system mode command  " -R.  
Sorry, can't help too much on this one...

**Comment by arcticfoxwp** [comment]
I did some troubleshooting. I restarted Homebridge again and now everything is correct:

[6/14/2023, 10:51:09 AM] [Envisalink-Ademco] The alarm system was not ready, and a zone fault was detected. The request for state change of undefined is ignored, review the alarm system keypad for more information.
