### ISSUE TITLE
Make sure TPI is enabled?

### ISSUE THREAD

**Issue by bmaranda** [haywirecoder/homebridge-envisalink-ademco#49]
Hello. I just installed your plugin in my HOOBS Raspberry machin to inference with with my EVL3 Ademco. You mention to make sure TPI is enabled. It is currently not enabled when i log directly on my EVL on my local network by using its IP. I contacted Envisalink support to get help. They told me that there was no such feature such as enabling the TPI. Is there something that I am doing wrong to enable the TPI feature using your plugin? Thanks.

<img width="728" alt="image" src="https://github.com/haywirecoder/homebridge-envisalink-ademco/assets/158232961/79757d67-9ccd-4b19-b7c7-3ceefcb16377">

**Comment by haywirecoder** [comment]
The screenshot shows  "Enabled TPI Session Alert" checked (e.g. enabled). This allows for a TPI session alert which is needed by the plug-in.  The TPI requirement is met.
