### ISSUE TITLE
Request: Periodically set clock on Envisalink

### ISSUE THREAD

**Issue by iTim314** [haywirecoder/homebridge-envisalink-ademco#51]
My Envisalink is connected to an Internet-less IoT network, and there cannot access the EyezOn servers to set its clock. While this probably doesn’t affect anything, I suspect this might be causing some delayed HomeKit notifications.

I found a stale Homebridge plugin that does this every hour, so I’m moderately confident it’s possible.

**Comment by haywirecoder** [comment]
Hi,

Are you talking about "homebridge-envisalink" plug-in?  This plug is designed to work with a DSC panel. That panel has a different code set including a method to set the panel clock using a single sequence command. Unfortunately, Ademco doesn't have such code set. To set the time on Ademco panel requires the sequence below.  To code this sequence could be problematic. For example send code sequence, waiting for a format text, send another code sequence, waiting for another format text...etc. While this sequence is running process other events, while checking for error conditions. This introduce too many possible errors and impact for this  plug-in for such a minor feature.


**Set Time this sequence:**
Enter your security code + [#] + [6] + [3]. When the time/date are displayed, press [*]. 
Enter the 2-digit hour setting, i.e., 18 for 6:00 pm. Press [*]. 
Enter the 2-digit minute setting, i.e., 14 for 2:14. Press [*]. 
Press [1] for PM and [2] for AM. Press [*]. 
To exit, press [*] when the cursor is at the last digit.
