### ISSUE TITLE
connect EHOSTUNREACH error

### ISSUE THREAD

**Issue by arcticfoxwp** [haywirecoder/homebridge-envisalink-ademco#55]
Hello,

Updated Homebridge to the latest version yesterday and immediately started getting the following error:

[9/28/2024, 5:04:03 PM] [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.130, port: 4025
[9/28/2024, 5:04:03 PM] [Envisalink-Ademco] EnvisaLink Network Error:  Error: connect EHOSTUNREACH 192.168.1.130:4025 - Local (192.168.1.65:53354)
    at internalConnect (node:net:1094:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at node:net:1324:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:545:9)
    at processTimers (node:internal/timers:519:7) {
  errno: -65,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.130',
  port: 4025

Evisalink Info

Type:EVL4 HW
Version:213
Local IP:192.168.1.130

**Comment by haywirecoder** [comment]
Hi,

The error EHOSTUNREACH indicates that when the TCP connection was attempted, the connection failed because the underlying protocol software could not find a network node route to the designated target node. The fix is somewhat operating system-dependent please refer to your OS guides and/or Homebridge installation. The plug-in requires you to have a stable network connection to the Envisalink module before using this plug-in.

**Comment by arcticfoxwp** [comment]
> Hi,
> 
> The error EHOSTUNREACH indicates that when the TCP connection was attempted, the connection failed because the underlying protocol software could not find a network node route to the designated target node. The fix is somewhat operating system-dependent please refer to your OS guides and/or Homebridge installation. The plug-in requires you to have a stable network connection to the Envisalink module before using this plug-in.

So I’ve been running the plugin for several years without issue, until yesterday. I can log into my Eyeson Envisalink dashboard and my alarm is online, and controllable from there. Everything is functioning correctly except for in Homebridge. The only thing that changed was the Homebridge ui update that was pushed yesterday. 

Is there anything I can try?

**Comment by haywirecoder** [comment]
Unfortunately, the error that you are getting is at the TCP/IP stack, the plug-in is just surfacing the message it is getting from Nodejs, so this is out scope and control of this plug-in. My guess is you have a network issue between your Homeridge server and the Envisakit module.  Some basic network troubleshooting would be to start rolling back any changes and determine if you can get back to a working state. Network commands such Ping, telneting to port 4025, and route trace can let you know if good connection between your Homebridge and the Envisakit module. Nodejs is the engine underneath Homebridge, so a quick search of Nodejs, EHOSTUNREACH, and OS name/version may yield some results.

**Comment by arcticfoxwp** [comment]
Found my answer! You can close, thanks for the help.

MacOS 15.0 / Sequoia
MacOS Sequoia introduce new function to control what applications have access to the network. If you have problems with connections, make sure 'node' has access to local network in macOS Settings > Privacy & Security > Local network (if there is no switch for 'node' try reinstalling node).

Homebridge logs could contains messages like this Error: connect EHOSTUNREACH 192.168.0.72:80
