### ISSUE TITLE
Support for Homebridge 2.0

### ISSUE THREAD

**Issue by iTim314** [haywirecoder/homebridge-envisalink-ademco#56]
Homebridge 2.0 is coming soon, and with it some breaking changes to plugins. Do we know if this plugin is compatible with v2.0 yet? 

I have not had a chance to run a beta instance and find out for myself.

**Comment by haywirecoder** [comment]
Hi,

I have not had the opportunity to install 2.0, the plan is to support 2.0.  However,  depending on the number of changes the updated version may be a few weeks after the release of 2.0.
