### ISSUE TITLE
Eyezon (Envisalink) Duo Honeywell Chime & Cancel Question

### ISSUE THREAD

**Issue by danielraffel** [haywirecoder/homebridge-envisalink-ademco#57]
Do you know how I can send a code to the EyezOn (Envisalink) Duo when arming or disarming my alarm when using the Home app to suppress the beeping sound?

Additionally, is there a way to program a command equivalent to pressing “Cancel” on the alarm keypad to clear any stuck messages that might prevent re-arming (e.g., a notification about a previous alarm event or a low battery warning)?

Thanks so much for making this integration, it works great!

**Comment by haywirecoder** [comment]
1. chimeToggle = true would create a switch in the homekit (Home), this will control the Chime (Bell) sound. You can also enable this using the UI.
2. You can use a speedkey (e.g. a switch) to send custom command sequences. However, you can indicate the zone is bypassable and create a bypass switch. In your the automation you can switch bypass on and it will auto-bypass these zones.

**Comment by danielraffel** [comment]
**Regarding #1: chime**
Well, it turns out the Chime and Arming Ding are separate features and I was conflating them:
- The chime feature is specifically for sensor openings (doors/windows).
- The arming “ding” for arming/disarming confirms that your code was entered successfully.

It is Possible to Modify the Arming Ding Confirmation on a Vista20P (*38)

This setting lets you choose whether the panel will emit the confirmation ding when arming/disarming. Here’s how to adjust it:
1.	Enter Installer Programming Mode:
•	Use the installer code (default is 4112) followed by 800.
•	Example: 4112800.
2.	Access Field *38:
•	Press *38 to access the arming confirmation ding setting.
3.	Set the Desired Option:
•	0: No confirmation ding (this will silence the arming/disarming beep).
•	1: Confirmation ding enabled for both wired keypads and RF keypads (default setting).
•	2: Confirmation ding enabled for RF keypads only.
•	Press the number corresponding to your preference (e.g., 0 to disable the beep).
4.	Exit Programming Mode:
•	Press *99 to save your changes and exit programming.

BTW, when I enabled the chime feature in the plugin (set it to true), toggling it in the Home app successfully disabled/enabled the chime feature on the keypad panel. The functionality was inverted (on was off and off was on), but it works!

**Regarding #2: Speed Keys / Bypass Switch**

Thanks for the suggestion! I’m trying to figure out how to send the equivalent of tapping "cancel" on the alarm keypad regardless of the zone or error message. I believe I usually just press the asterisk (*) key, and that seems to work, but I’m not sure how to integrate this into the plugin settings. Would I just add * as a macro like this?

<img width="740" alt="image" src="https://github.com/user-attachments/assets/a7d8bf88-0a3d-47fe-a743-ecc1fd11494a" />

**Comment by haywirecoder** [comment]
Hi,
The process you just defined is considered panel programming, which the plug-in doesn't support for multiple reasons. Partly because the plug-in would have to start understanding various specific sequence outputs from the panel (e.g. if this prompt do X, then wait for Y, then send Z ...etc) this is out scope.  
The macro is design for sequence inputs (non-program) such as turn-on trigger Fire alert.  You could create a macro on the Vista20 panel itself that could do what your suggesting and then assign that custom to this sequence. But, that digging into program manual for Vista 20.

**Comment by danielraffel** [comment]
Got it. While experimenting, I found that to “clear” or “cancel” a message on my alarm panel, I have to enter my alarm code followed by “off.” Probably not something I should automate with a macro on my panel. 😉

The main reason I’d like to handle this remotely is that if my alarm enters an error state (e.g., an error message on the panel), I can’t set the alarm remotely until the error is cleared. If you have any other suggestions for managing this, I’d love to hear them!

**Comment by haywirecoder** [comment]
I completely understand your goal and it is a concern when it comes to remote arming. My only advice is to create a bypass switch either by manually indicating the zones that can be bypassed or enabling in your panel global bypass command (e.g. <pin>#6) and always running bypass before the alarm command (this ofcourse creates a new set of security issues).  It doesn't fix every possible issue but covers many problems that would prevent the alarm from arming, such as low battery, someone leaving the upstairs windows open, or temporary RF jamming...etc.
