### ISSUE TITLE
Support for Push Notifications via Tripped Modes in Home, Away, Night?

### ISSUE THREAD

**Issue by danielraffel** [haywirecoder/homebridge-envisalink-ademco#58]
Is it possible to use the [Envisacor Ademco Plugin](https://github.com/haywirecoder/homebridge-envisalink-ademco) to receive a critical alert from the Home App if the alarm is tripped when in Home, Night or Away mode?

**Comment by haywirecoder** [comment]
I am not clear on the request. Today, if the alarm triggers a critical alert is generated from Home App. When these critical alert is generate is dependent of what triggered your alarm. If your panel has "trigger" events in Home mode, the plug will show that as critical alert.

**Comment by danielraffel** [comment]
Can confirm this works.
