### ISSUE TITLE
Support for adjusting the alarm using geofence triggers and receive push notifications for alarm state changes?

### ISSUE THREAD

**Issue by danielraffel** [haywirecoder/homebridge-envisalink-ademco#59]
Is it possible to use the [Envisacor Ademco Plugin](https://github.com/haywirecoder/homebridge-envisalink-ademco) to adjust the alarm state and receive a push notifications for the state change from the Apple Home app?

**What I tried:**
I set up dummy switches in the “first arrive/last leave” automations to trigger changes to the security modes managed by the Envisacor Ademco Plugin through additional automations that adjust the alarm state when the dummy switch is activated. While this setup successfully changes the alarm states, I was unable to receive push notifications for alarm state changes in the Apple Home app.

_Note: I managed to use the [homebridge-pushover plugin](https://github.com/meg768/homebridge-pushover) to send push notifications via [Pushover](http://pushover.net/), but I was hoping to rely solely on Apple Home for my notifications._

**Request**
Would it be possible for the plugin to:
• Provide mode switches that can bypass HomeKit confirmations and trigger notifications?
• Allow these mode switches to update the Security System Target State characteristic, resulting in a notification within the HomeKit protocol? From my understanding, triggering a notification should be feasible when done via a switch.

**Comment by haywirecoder** [comment]
The plug-in already support the native Homekit notifications for an system alarm.  So changing the arming states does come up as a notification. I personally see this each time my panel change arm state from Home, away...etc... via the app or on the alarm panel itself. I also have an automation to change state at specific times, which also show the notification. I would look at the security tile for alarm system and confirm the notifications is enabled.

**Comment by danielraffel** [comment]
**The issue I am experiencing is specific to adjusting the alarm based off geofence triggers.**

I can confirm that push notifications (including critical alerts) work when I manually trip or adjust the alarm. In fact, my alarm company just called. 🤣 Additionally, automating an alarm mode schedule also triggers a push notification.

What I haven’t confirmed is whether the “first person arrives/last person leaves” automations will send push notifications **when triggered via geofence**. Previously, when I tried using this plugin’s alarm mode to arm on “last person leaves” or disarm on “first person arrives,” I recall being prompted with a push notification to confirm the state change when people triggered those automations based off geofence. However, when I replaced those automations with two dummy switches (one for “first person arrives” and another for “last person leaves”) and then created separate automations to listen to these switches and adjust the alarm arm/disarm mode accordingly, the alarm state was successfully adjusted by geofence—**but no push notification was sent**!

To my understanding, geofence-based triggers for sensitive devices like alarms, locks, and garages require user authentication to allow changes in the Home app. This restriction does not apply to other automations, such as scheduled triggers or dummy switches, adjusting these devices.

What’s unclear is why a scheduled trigger for the alarm sends a push notification, but adjusting the alarm state via dummy switch automations does not. I do know that other plugins have implemented mode switches that work with geofence triggers to adjust alarm states and send Apple Home push notifications.

In the example of [this plugin](https://github.com/MiguelRipoll23/homebridge-securitysystem), the approach appears to work as follows:
	1.	Mode Switches Creation:
The plugin adds mode switches in SecuritySystem.prototype.services, such as:
	•	modeHomeSwitchService (Stay Arm)
	•	modeAwaySwitchService (Away Arm)
	•	modeNightSwitchService (Night Arm)
	•	modeOffSwitchService (Disarm)
Example:

this.modeHomeSwitchService = new Service.Switch(options.modeHomeSwitchName, "mode-home");


	2.	One-Way Switches:
Each mode switch is implemented as a standard HomeKit Switch service that can only be turned ON:

setModeHomeSwitch(value, callback) {
  if (value === false) {
    callback(HK_NOT_ALLOWED_IN_CURRENT_STATE, false);
    return;
  }
  this.updateTargetState(
    Characteristic.SecuritySystemTargetState.STAY_ARM,
    originTypes.INTERNAL,
    true,
    null
  );
  callback(null);
}


	3.	Behavior When Activated:
Turning a mode switch ON does the following:
	•	Updates the security system’s target state using updateTargetState().
	•	Updates the HomeKit SecuritySystemTargetState characteristic.
	•	Resets all other mode switches to OFF.

Using these mode switches in the first person/last person automations, I can use geofence triggers to adjust alarm modes and still receive push notifications, which is something I cannot currently achieve using dummy switch automations or this plugins modes.

**Comment by haywirecoder** [comment]
Hi,  

The sample plug-in provided is a basic implementation, as it does not connect to an actual alarm system. This plug-in reads the alarm stream (e.g., EnvisaLink TPI) to gather information about various states and updates the `SecuritySystem` state accordingly. For details on how the alarm is processed when different modes are activated, refer to the `setTargetState` function in `partitionAccessory.js`. Additionally, the `systemUpdate` function in `index.js` handles alarm responses from the Envisalink TPI interface.  

If the goal is to create a button for each alarm state (e.g., disarm, away, etc.), you can achieve this by creating "speedkeys" (custom switches) for each operation. These speedkeys use raw command strings in the format `<PIN><Ademco Alarm Command>`. Each speedkey sends a direct command to the EnvisaLink TPI. Just like other operations performed on the panel, the plug-in reads the Envisalink TPI stream and updates the state accordingly.  You can get various alarm command from the tpi.js under 'exports.alarmcommand'

For example:  

```json
"speedkeys": [
    {
        "name": "Disarm",
        "speedcommand": "@pin1"
    },
    {
        "name": "Away",
        "speedcommand": "@pin2"
    }
]
```

In my opinion, Apple has good reasoning behind its prompting mechanism, so I personally wouldn’t recommend the approach you’re trying to implement. However, the plug-in as it stands gives you the flexibility to do so if needed.  

---

**Comment by danielraffel** [comment]
Amazing. That was exactly what I was looking for. I can confirm that works perfectly. What a great plugin. And, what fantastic and patient developer support you've provided to me. 🙇

I wrote up a blog post explaining how I got this working. No pressure to read it but if you do and have any feedback please lmk.

https://danielraffel.me/2024/12/06/how-to-set-up-your-honeywell-alarm-with-apple-home-for-push-notifications-and-geofence-based-arming-disarming/

By the way, is there a way to add a name to the configuration so that each speedkey switch has a descriptive name? It’s not a big deal to rename them later, if not possible, which is what I did.

**Comment by haywirecoder** [comment]
Interesting ---  "Each switch has a descriptive name and not show it"  It should show the description provided by the "name" field you.  Have you tried to ungroup?  Either-way, I will look into why the correct name is not appearing.

**Comment by danielraffel** [comment]
Yeah, I did ungroup and they still had the same names. It wasn’t hard to toggle each to determine what they did and rename them in the home app, so that’s what I did. But, figured I’d report if useful feedback.


![](https://danielraffel.me/content/images/2024/12/Screenshot-2024-12-17-at-11.38.16-AM.png)

But, then after renaming them I decided to re-group them since I kinda preferred them collapsed.

![](https://danielraffel.me/content/images/2024/12/renamed.png)

**Comment by haywirecoder** [comment]
Awesome...glad you got it working for you. I will look at the speed keys initial setup code and make a few adjustment in next version to hopefully avoid that initial configuration oddness.

**Comment by danielraffel** [comment]
If you’re open to it, it might be useful to others to document the speed keys code example you shared with me in the readme. Explaining how to use it in first/last automations, even if it includes a disclaimer, might be helpful for folks interested in trying out presence based automation. Obviously understand if you don't want to but it's a nice tip!
