### ISSUE TITLE
Envisilink Plugin causing SIGTERM shutdown when run in Automation

### ISSUE THREAD

**Issue by sebastiangoldstein** [haywirecoder/homebridge-envisalink-ademco#6]
Hello, 
I'm kind of a NOOB so I will describe this issue as best as I can.

Since the last update (Aug 1) it appears that this plugin has been throwing a "SIGTERM" (whatever that means) when I run my HomeKit"Good Morning" Automation which shuts off the alarm. 
The result is that my HOOBS server stops running.
This is not an issue when I arm or disarm the alarm through the Apple Home App but it does happen every morning when the "Good Morning" Automation is run.
It should be noted that on most mornings the alarm has already been disarmed by my wife before the "Good Morning" Automation is run (so I am turning off an alarm that is already off) however I don't believe that should make a difference. 
A log example is below. 

8/28/2020, 7:49:11 AM INFO: [Device Event]: (Loft Lamp) [SWITCH] is on
8/28/2020, 7:49:15 AM INFO: [Device Event]: (Dining Chandelier) [LEVEL] is 100
8/28/2020, 7:49:15 AM INFO: [Device Event]: (Dining Chandelier) [SWITCH] is on
8/28/2020, 7:49:16 AM INFO: [Device Event]: (Loft Lamp) [LEVEL] is 100
8/28/2020, 7:49:20 AM [Envisalink-Ademco] Alarm request did not return successful in allocated time, setting status to READY
8/28/2020, 7:49:20 AM TypeError: Cannot set property 'lastTargetState' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-envisalink-ademco/index.js:465:38
    at EnvisalinkAccessory.getAlarmState (/home/hoobs/.hoobs/node_modules/homebridge-envisalink-ademco/index.js:409:13)
    at EnvisalinkAccessory.proccessAlarmTimer (/home/hoobs/.hoobs/node_modules/homebridge-envisalink-ademco/index.js:463:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
8/28/2020, 7:49:20 AM ERROR: uncaughtException: Cannot set property 'lastTargetState' of undefined
8/28/2020, 7:49:20 AM TypeError: Cannot set property 'lastTargetState' of undefined
8/28/2020, 7:49:20 AM at /home/hoobs/.hoobs/node_modules/homebridge-envisalink-ademco/index.js:465:38
8/28/2020, 7:49:20 AM at EnvisalinkAccessory.getAlarmState (/home/hoobs/.hoobs/node_modules/homebridge-envisalink-ademco/index.js:409:13)
8/28/2020, 7:49:20 AM at EnvisalinkAccessory.proccessAlarmTimer (/home/hoobs/.hoobs/node_modules/homebridge-envisalink-ademco/index.js:463:18)
8/28/2020, 7:49:20 AM at listOnTimeout (internal/timers.js:549:17)
8/28/2020, 7:49:20 AM at processTimers (internal/timers.js:492:7)
8/28/2020, 7:49:20 AM Got SIGTERM, shutting down Bridge...

**Comment by haywirecoder** [comment]
Hi, 
I have seen this error recently and been testing correction for the past week on my local installation. I will release an update (1.1.7) this weekend that hopefully address this issue.

**Comment by haywirecoder** [comment]
version 1.1.7 has been release. The update fixes this issues.
